fix "komodo_to_cix.py" run to avoid this python env error during "bk build":
    ...
      import _SilverCity
    ImportError: dynamic module does not define init function (init_SilverCity) 

This is what our "mozpython" is for.

(integrated from komodo (trunk) change 55467 by trentm)

git-svn-id: https://svn.openkomodo.com/repos/openkomodo/trunk@5967 b87d16e7-d29f-4ee1-b5ec-817d645d335f