guard against the catalog zone of the database being simultaneously updated in two separate threads. This can result in this assertion:
AssertionError: codeintel: Python '_win32sysloader' blob in `...\codeintel2\catalogs\pywin32.cix' collides with existing Python '_win32sysloader' blob (from res_id 0) in catalog (XXX haven't decided how to
deal with that yet)

r=toddw

(integrated from komodo (trunk) change 19326 by trentm)

git-svn-id: https://svn.openkomodo.com/repos/openkomodo/trunk@1466 b87d16e7-d29f-4ee1-b5ec-817d645d335f